on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      # Чекаутим код
      - name: Checkout repository
        uses: actions/checkout@v3
      # Устанавливаем python нужной версии
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'
          architecture: 'x64'
      # Устанавливаем зависимости
      - name: Install requirements
        run: pip install -r requirements.txt
      # Запускаем тесты
      - name: Run tests
        run: python -m pytest
      - name: Run black
        run: python -m black --diff --check src/
      - name: Run isort
        run: python -m isort --check-only --profile black src/
      - name: Run flake8
        run: python -m flake8 src/
